#
# (C) Copyright 2017
# Thomas Schaefer, Kontron Europe GmbH, thomas.schaefer@kontron.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_EMB_EEP_I2C_EEPROM) += emb_eep.o

ifndef CONFIG_SPL_BUILD
obj-$(CONFIG_CMD_KBOARDINFO) += cmd_kboardinfo.o
endif
